name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'  # Cambia a la versión de Go que desees usar

      - name: Install dependencies
        run: go mod tidy  # Instala las dependencias definidas en go.mod

      - name: Run tests
        run: go test -v ./...  # Ejecuta todas las pruebas en el paquete

      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -html=coverage.out -o coverage.html  # Genera un informe de cobertura en formato HTML

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.html  # Sube el informe de cobertura generado

      - name: Notify on failure
        if: failure()
        run: |
          echo "Build failed, please check the logs."


    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
